[project]
name = "fastapi-1"
version = "0.1.0"
description = "My learning FastAPI project"
authors = [{name = "Your Name", email = "your.email@example.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "uvicorn>=0.34.3",
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.5",
    "environs>=14.2.0",
    "itsdangerous>=2.2.0"
]

[tool.poetry]
packages = [{ include = "fastapi_1", from = "src" }]

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.0"

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["venv", ".venv", "alembic", "docker", ".git", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501", "B008"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.params.Depends"
]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "start:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
asyncio_mode = "auto"
addopts = "-vv"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"



