"""add_review_check_unique_constraints_and_movie_rating_column

Revision ID: 0eedff6c3fd0
Revises: d363dd23c267
Create Date: 2026-07-05 18:58:37.860027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eedff6c3fd0'
down_revision: Union[str, Sequence[str], None] = 'd363dd23c267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_movies_rating'), 'movies', ['rating'], unique=False)
    op.create_unique_constraint('uq_review_user_id_movie_id', 'reviews', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_user_id_movie_id', 'reviews', type_='unique')
    op.drop_index(op.f('ix_movies_rating'), table_name='movies')
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###
