"""add_server_default_random_uuid

Revision ID: 4586bbb36d9e
Revises: fefc0f29796e
Create Date: 2026-07-12 16:45:11.976446

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4586bbb36d9e"
down_revision: Union[str, Sequence[str], None] = "fefc0f29796e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movies", "id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("users", "id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("reviews", "id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("directors", "id", server_default=sa.text("gen_random_uuid()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movies", "id", server_default=None)
    op.alter_column("users", "id", server_default=None)
    op.alter_column("reviews", "id", server_default=None)
    op.alter_column("directors", "id", server_default=None)
    # ### end Alembic commands ###
