"""initial

Revision ID: 5de9ac7fff83
Revises: 
Create Date: 2026-06-28 16:01:07.783564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de9ac7fff83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('reviews_user_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.drop_index(op.f('role_permissions_permission_id'), table_name='role_permissions')
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.drop_index(op.f('user_roles_role_id'), table_name='user_roles')
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.create_index(op.f('user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.create_index(op.f('role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.create_index(op.f('reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('reviews_created_at'), 'reviews', ['created_at'], unique=False)
    # ### end Alembic commands ###
