"""add_movie_domain_tables

Revision ID: 754b8517ec60
Revises: 5de9ac7fff83
Create Date: 2026-06-28 18:19:28.834685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754b8517ec60'
down_revision: Union[str, Sequence[str], None] = '5de9ac7fff83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('directors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('director_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.CheckConstraint('release_year >= 1895 AND release_year <= EXTRACT(YEAR FROM NOW())', name='check_release_year'),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_director_id'), 'movies', ['director_id'], unique=False)
    op.create_index(op.f('ix_movies_release_year'), 'movies', ['release_year'], unique=False)
    op.create_table('country_movies',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'country_id')
    )
    op.create_index(op.f('ix_country_movies_country_id'), 'country_movies', ['country_id'], unique=False)
    op.create_table('genre_movies',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_index(op.f('ix_genre_movies_genre_id'), 'genre_movies', ['genre_id'], unique=False)
    op.add_column('reviews', sa.Column('movie_id', sa.Uuid(), nullable=False))
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reviews_movie_id'), 'reviews', ['movie_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_movie_id'), table_name='reviews')
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'movie_id')
    op.drop_index(op.f('ix_genre_movies_genre_id'), table_name='genre_movies')
    op.drop_table('genre_movies')
    op.drop_index(op.f('ix_country_movies_country_id'), table_name='country_movies')
    op.drop_table('country_movies')
    op.drop_index(op.f('ix_movies_release_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_director_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_table('genres')
    op.drop_table('directors')
    op.drop_table('countries')
    # ### end Alembic commands ###
