"""add_trgm_index_for_movies_title

Revision ID: 7e08230fa757
Revises: 9afffc74e4d8
Create Date: 2026-07-16 19:42:23.802595

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e08230fa757"
down_revision: Union[str, Sequence[str], None] = "9afffc74e4d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index(
        "movie_search_trgm_idx",
        "movies",
        [sa.literal_column("title gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("movie_search_trgm_idx", table_name="movies")
    # ### end Alembic commands ###
