"""add_indexes_for_reviews_rating_reviews_updated_at

Revision ID: 9afffc74e4d8
Revises: 4586bbb36d9e
Create Date: 2026-07-16 19:28:43.602615

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9afffc74e4d8"
down_revision: Union[str, Sequence[str], None] = "4586bbb36d9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_reviews_rating"), "reviews", ["rating"], unique=False)
    op.create_index(
        op.f("ix_reviews_updated_at"), "reviews", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_updated_at"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_rating"), table_name="reviews")
    # ### end Alembic commands ###
