"""add_check_unique_constraints_and_date_of_birth_column

Revision ID: d363dd23c267
Revises: 754b8517ec60
Create Date: 2026-06-30 17:42:45.563225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd363dd23c267'
down_revision: Union[str, Sequence[str], None] = '754b8517ec60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directors', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.create_unique_constraint('uq_director_full_name_date_of_birth', 'directors', ['first_name', 'last_name', 'date_of_birth'])
    op.create_unique_constraint('uq_movie_title_year_director', 'movies', ['title', 'release_year', 'director_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_movie_title_year_director', 'movies', type_='unique')
    op.drop_constraint('uq_director_full_name_date_of_birth', 'directors', type_='unique')
    op.drop_column('directors', 'date_of_birth')
    # ### end Alembic commands ###
