"""change_movie_rating_to_float

Revision ID: dd2399065b0b
Revises: 0eedff6c3fd0
Create Date: 2026-07-06 16:30:48.455944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2399065b0b'
down_revision: Union[str, Sequence[str], None] = '0eedff6c3fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
