"""add_trgm_index_for_directors

Revision ID: fefc0f29796e
Revises: dd2399065b0b
Create Date: 2026-07-07 17:52:33.685650

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fefc0f29796e"
down_revision: Union[str, Sequence[str], None] = "dd2399065b0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index(
        "directors_search_trgm_idx",
        "directors",
        [sa.literal_column("(first_name || ' ' || last_name) gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("directors_search_trgm_idx", table_name="directors")
    # ### end Alembic commands ###
